Update sdk-extractor.yml

diff --git a/.github/workflows/sdk-extractor.yml b/.github/workflows/sdk-extractor.yml
--- a/.github/workflows/sdk-extractor.yml
+++ b/.github/workflows/sdk-extractor.yml
@@ -14,13 +14,21 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download SDK
-        run: wget https://github.com/arichornlover/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS18.0.sdk.zip
+        run: |
+          mkdir extracted_folder
+          curl -LJO https://github.com/arichornlover/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS18.0.sdk.zip
 
       - name: Unpack SDK
-        run: unzip iPhoneOS18.0.sdk.zip
-
+        run: |
+          if [ -f iPhoneOS18.0.sdk.zip ]; then
+            unzip iPhoneOS18.0.sdk.zip -d extracted_folder
+          else
+            echo "Failed to download the SDK ZIP file"
+            exit 1
+          fi
+      
       - name: Move files
-        run: mv iPhoneOS18.0.sdk/* .
+        run: mv extracted_folder/* .
       
       - name: Commit changes
         run: |
